### ISSUE TITLE
rbenv plugins always cause puppet changes

### ISSUE THREAD

**Issue by rudolfs** [alup/puppet-rbenv#109]
When using additional rbenv plugins, they always get updated with "git pull", this causes a puppet change even if there are no updates to the plugins. Plugin updates should only trigger a puppet change when git pull actually does something. Here's the pull request to fix this: https://github.com/alup/puppet-rbenv/pull/108

**Comment by alup** [comment]
Thanks for mentioning and fixing the issue.
